Testbox custom dockerfile
toptal/testbox_bookstore_api pull request #18
Opened 2022-01-31 09:09 UTC by mrzasa

2022-01-31 10:30 UTC, p0deje reviewed
To ensure it this dockerfile goes through the templating logic of Testbox, let's change its CMD to `bash`. If the container starts successfully, it would mean that Testbox ran `scripts.start` successfully. Otherwise, the container would not run Rails server and tests would fail.

2022-02-04 03:42 UTC, p0deje approved these changes

2022-02-04 08:37 UTC, kml requested changes
As long as it's test then fine, but I don't think that this should be merge to master.
What dockerfile will be picked is part of testbox unit tests.

2022-02-04 12:26 UTC, mrzasa commented
Closing after the discussion with @kml

2022-02-04 12:26 UTC, closed without merging